name: foodsora
description: A food application

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  intl_utils: ^2.6.1
  json_annotation: ^4.4.0
  path: ^1.8.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_intl:
  main_locale: en_US
  enabled: true
